winetree94:
  children:
    workers:
      hosts:
        winetree94.click:
        winetree94.micropc:
        winetree94.opi5b:
    storages:
      hosts:
        winetree94.hc4:

linode:
  hosts:
    winetree94.linode:
