- name: Worker Setup
  hosts: storages
  become: true
  become_user: root

  tasks:
    - name: Install depencencies
      ansible.builtin.apt:
        pkg:
          - nfs-kernel-server
          - rsync

    - name: Mount Main Storage
      ansible.posix.mount:
        path: /vol/main
        src: UUID=d426c995-d24b-4541-8866-84b339e84f20
        fstype: ext4
        opts: noatime
        state: mounted
        boot: true

    - name: Mount Backup Storage
      ansible.posix.mount:
        path: /vol/backup
        src: UUID=b53b8f17-5e1e-47da-9aa8-55301de12c6d
        fstype: ext4
        opts: noatime
        state: mounted
        boot: true

    - name: Allow hosts
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: /vol/main 192.168.0.*(rw,async,no_root_squash,no_subtree_check)

    - name: Start nfs nfs-kernel-server
      ansible.builtin.service:
        name: nfs-kernel-server
        state: started
        enabled: true
