- name: Apt Manager
  hosts: all

  tasks:
    - name: Update package
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
        autoremove: true
        upgrade: full
