- name: Worker Setup
  hosts: workers

  tasks:
    - name: Install depencencies
      become: true
      become_user: root
      ansible.builtin.apt:
        name: nfs-common

    - name: Mount nfs storage
      become: true
      become_user: root
      ansible.posix.mount:
        src: 192.168.0.243:/
        path: /nfs
        opts: "rw,async,hard,x-systemd.automount,x-systemd.requires=network-online.target"
        state: unmounted
        boot: false
        fstype: nfs4
